<a href="https://colab.research.google.com/github/Tarun-pandit/Data_Science_practice/blob/DATA_analysis_using_NUMPY/3_Multidimensional_Indexing_and_Axis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
arr = np.array([
 [1,2,3],
 [4,5,6],
 [7,8,9]
])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
np.sum(arr,axis=0)

array([12, 15, 18])

In [ ]:
np.sum(arr,axis=1)

array([ 6, 15, 24])

In [ ]:
arr[0,1]

np.int64(2)

In [ ]:
arr[0:2, 1:3]

array([[2, 3],
       [5, 6]])

In [ ]:
arr3D = np.array([
 [[1, 2, 3], [4, 5, 6]],
 [[7, 8, 9], [10, 11, 12]]
])
display(arr3D)

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [ ]:
arr3D[0,1,2]

array([4, 5, 6])

In [ ]:
arr3D[:,0,:]

array([[1, 2, 3],
       [7, 8, 9]])