<a href="https://colab.research.google.com/github/Tarun-pandit/Data_Science_practice/blob/DATA_analysis_using_NUMPY/6_Built_in_Mathematical_Functions_in_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

np.mean() – Compute the **mean** (average) of an array.





In [ ]:
np.mean(arr)

np.float64(5.0)

np.std() – Compute the **standard deviation ** of an array.

In [ ]:
np.std(arr)

np.float64(2.581988897471611)

np.var() – Compute the **variance** of an array.

In [ ]:
np.var(arr)

np.float64(6.666666666666667)

np.min() – Compute the **minimum** value of an array.

In [ ]:
np.max(arr)

np.int64(9)

np.sum() – Compute the **sum** of all elements in an array.

In [ ]:
np.sum(arr)

np.int64(45)

np.prod() – Compute the **product** of all elements in an array.

In [ ]:
np.prod(arr)

np.int64(362880)

np.median() – Compute the **median** of an array.

In [ ]:
np.median(arr)

np.float64(5.0)

`np.percentile()` computes the q-th percentile of the data along the specified axis. Here, it calculates the 50th percentile, which is the median.

In [ ]:
np.percentile(arr, 50)  # For the 50th percentile (median)

np.float64(5.0)

`np.argmin()` returns the indices of the minimum values along an axis. In this case, it returns the index of the minimum value in the flattened array.

In [ ]:
np.argmin(arr)

np.int64(0)

`np.argmax()` returns the indices of the maximum values along an axis. In this case, it returns the index of the maximum value in the flattened array.

In [ ]:
np.argmax(arr)

np.int64(8)

`np.corrcoef()` returns the Pearson product-moment correlation coefficients of a dataset. It calculates the correlation matrix between the rows of the input arrays.

In [ ]:
np.corrcoef(arr, arr2)

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

`np.unique()` returns the sorted unique elements of an array.

In [ ]:
np.unique(arr)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

`np.diff()` calculates the n-th discrete difference along the given axis. By default, it calculates the difference between consecutive elements along the last axis.

In [ ]:
np.diff(arr)

array([[1, 1],
       [1, 1],
       [1, 1]])

`np.cumsum()` returns the cumulative sum of the elements along a given axis. By default, it calculates the cumulative sum along the flattened array.

In [ ]:
np.cumsum(arr)

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45])

`np.linspace()` returns evenly spaced numbers over a specified interval. It takes the start, stop, and number of samples to generate.

In [ ]:
np.linspace(0, 10, 5)  # 5 numbers from 0 to 10

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

`np.log()` calculates the natural logarithm of each element in the input array.

In [ ]:
np.log(arr)

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947],
       [1.94591015, 2.07944154, 2.19722458]])

`np.exp()` calculates the exponential of each element in the input array.

In [ ]:
np.exp(arr)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02],
       [1.09663316e+03, 2.98095799e+03, 8.10308393e+03]])

# ***These methods are used for performing mathematical and statistical operations with NumPy***

`np.mean()`: This function calculates the arithmetic mean (average) of the elements in a NumPy array. It sums up all the elements and divides by the total number of elements.

`np.std()`: This function computes the standard deviation of the elements in a NumPy array. The standard deviation is a measure of the amount of variation or dispersion of a set of values. A low standard deviation indicates that the values tend to be close to the mean, while a high standard deviation indicates that the values are spread out over a wider range.

`np.var()`: This function calculates the variance of the elements in a NumPy array. The variance is the average of the squared differences from the mean. It is another measure of the spread or dispersion of a dataset.

`np.min()`: This function finds the minimum value among all the elements in a NumPy array.

`np.sum()`: This function calculates the sum of all the elements in a NumPy array.

`np.prod()`: This function computes the product of all the elements in a NumPy array. It multiplies all the elements together.

`np.median()`: This function calculates the median of the elements in a NumPy array. The median is the middle value in a dataset that is ordered from least to greatest. If there is an even number of elements, the median is the average of the two middle values.

`np.percentile(arr, 50)`: This function computes the q-th percentile of the data along the specified axis. The 50th percentile is equivalent to the median, representing the value below which 50% of the data falls.

`np.argmin()`: This function returns the indices of the minimum values along an axis. If the array is flattened, it returns the index of the overall minimum value. You can specify an axis to find the minimum index along that axis.

`np.argmax()`: This function returns the indices of the maximum values along an axis. If the array is flattened, it returns the index of the overall maximum value. You can specify an axis to find the maximum index along that axis.

`np.corrcoef(arr, arr2)`: This function returns the Pearson product-moment correlation coefficients of a dataset. It calculates the correlation matrix between the rows of the input arrays. The correlation coefficient measures the linear relationship between two sets of data.

`np.unique()`: This function returns the sorted unique elements of an array. It removes duplicate values and returns the remaining elements in ascending order.

`np.diff()`: This function calculates the n-th discrete difference along the given axis. By default, it calculates the difference between consecutive elements along the last axis. This is useful for finding the rate of change between elements.

`np.cumsum()`: This function returns the cumulative sum of the elements along a given axis. By default, it calculates the cumulative sum along the flattened array. Each element in the output array is the sum of all previous elements up to that point.

`np.linspace(0, 10, 5)`: This function returns evenly spaced numbers over a specified interval. It takes the start value, stop value, and the number of samples to generate (inclusive of the stop value). This is useful for creating sequences of numbers for plotting or other calculations.

`np.log(arr)`: This function calculates the natural logarithm (base e) of each element in the input array. It applies the logarithm function element-wise.

`np.exp(arr)`: This function calculates the exponential of each element in the input array. It raises 'e' (Euler's number) to the power of each element in the array element-wise.