<a href="https://colab.research.google.com/github/Tarun-pandit/Data_Science_practice/blob/NUMPY/Add_basic_NumPy_array_creation_and_manipulation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
!pip install numpy

In [9]:
arr = np.array([1,2,3])
arr
arr1 = np.array([[1,2,3],[4,5,6]])
arr1



array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
np.zeros((3,3))


array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [13]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [14]:
np.full((3,3),5)

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [15]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [17]:
np.arange(1,100,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [18]:
np.linspace(1,100,5)

array([  1.  ,  25.75,  50.5 ,  75.25, 100.  ])

In [19]:
myarr = np.array([[1,2,3,4],[5,6,7,8]])
myarr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [23]:
myarr.shape

(2, 4)

In [25]:
myarr.size


8

In [26]:
myarr.dtype


dtype('int64')

In [27]:
myarr.ndim

2

In [32]:
myarr = np.array([[1,2,3,4],[5,6,7,8]],dtype='float32')
myarr
myarr.dtype

dtype('float32')

In [34]:
reshaped= myarr.reshape(4,2)
reshaped

array([[1., 2.],
       [3., 4.],
       [5., 6.],
       [7., 8.]], dtype=float32)