<a href="https://colab.research.google.com/github/Tarun-pandit/Data_Science_practice/blob/NUMPY/numpy_array_manipulation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
# Create a NumPy array with 4 rows and 3 columns
arr = np.array([[1,2,3], [4,5,6], [7,8,9],[11,12,13]])
# Display the array
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [11, 12, 13]])

In [ ]:
# Flatten the array 'arr' into a 1-dimensional array
flat = arr.flatten()
# Display the flattened array
flat

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 11, 12, 13])

In [ ]:
# Access the element at index 0 of the flattened array 'flat'
flat[0]

np.int64(1)

In [ ]:
# Slice the flattened array 'flat' to get elements from the beginning up to index 5 (exclusive)
flat[:5]

array([1, 2, 3, 4, 5])

In [ ]:
# Slice the flattened array 'flat' to get elements from index 3 (inclusive) to the end
flat[3:]

array([ 4,  5,  6,  7,  8,  9, 11, 12, 13])

In [ ]:
# Slice the flattened array 'flat' to get elements from index 3 (inclusive) up to index 13 (exclusive)
flat[3:13]

array([ 4,  5,  6,  7,  8,  9, 11, 12, 13])

In [ ]:
# Slice the flattened array 'flat' to get elements with a step of 2 (every other element)
flat[::2]

array([ 1,  3,  5,  7,  9, 12])

In [ ]:
# Slice the flattened array 'flat' from index 3 to 7 (exclusive) and create a copy
b = flat[3:7].copy() ##+++++++++++++3.
# Display the new array 'b'
b

array([4, 5, 6, 7])

In [ ]:
# Change the element at index 0 of array 'b'
b[0] = 4444666

In [ ]:
# Display array 'b' after modification
b

array([4444666,       5,       6,       7])

In [ ]:
# Display the original flattened array 'flat' to show that changing 'b' did not affect 'flat' (because .copy() was used)
flat

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 11, 12, 13])

In [ ]:
# Create a new NumPy array
arr1 = np.array([1,54,23,2,3,4,30,5,6])
# Use fancy indexing to select elements at indices 1, 4, and 6 from 'arr1'
arr1[[1,4,6]]

array([54,  3, 30])

In [ ]:
# Use boolean indexing to select elements from 'arr1' that are greater than 3
arr1[arr1>3]

array([54, 23,  4, 30,  5,  6])

In [ ]:
import numpy as np

# Create a 3x3 array filled with random numbers
random_arr = np.random.rand(3, 3)

# Print the shape of the array
print("Shape of the random array:", random_arr.shape)

# Display the array
display(random_arr)

Shape of the random array: (3, 3)


array([[0.89169164, 0.36688028, 0.97477493],
       [0.84036624, 0.94114861, 0.12631947],
       [0.03809538, 0.45878251, 0.99741059]])

In [ ]:
# Create your own unique float array
my_float_array = np.array([[1.5, 2.3, 3.8], [4.1, 5.9, 6.2], [7.7, 8.0, 9.5]])

# Convert the float array to an integer array
my_integer_array = my_float_array.astype(int)

# Display the integer array
display(my_integer_array)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
import numpy as np

# 1. Use fancy indexing to extract even numbers
arr_fancy = np.array([1, 2, 3, 4, 5, 6])
even_indices = [1, 3, 5] # Indices of even numbers
even_numbers = arr_fancy[even_indices]
print("Even numbers using fancy indexing:", even_numbers)

Even numbers using fancy indexing: [2 4 6]


In [ ]:
import numpy as np

# 2. Reshape a 1D array of size 9 into a 3x3 matrix
arr_1d = np.arange(9) # Create a 1D array from 0 to 8
arr_3x3 = arr_1d.reshape((3, 3))
print("Reshaped 3x3 matrix:")
display(arr_3x3)

Reshaped 3x3 matrix:


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
import numpy as np

# 3. Use boolean masking to filter numbers greater than 50
arr_mask = np.array([10, 60, 30, 80, 20, 70, 40, 90])
greater_than_50_mask = arr_mask > 50
filtered_numbers = arr_mask[greater_than_50_mask]
print("Numbers greater than 50 using boolean masking:", filtered_numbers)

Numbers greater than 50 using boolean masking: [60 80 70 90]
